# Generated by Django 4.2 on 2026-03-11 22:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0002_host_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('agent', 'Agent'), ('browser', 'Browser Extension')], default='unknown', max_length=50)),
                ('log_source', models.CharField(choices=[('NetworkMonitor', 'Network Monitor'), ('FileIntegrityMonitor', 'File Integrity Monitor'), ('ProcessMonitor', 'Process Monitor')], default='unknown', max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hosts.host')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
