# Generated by Django 4.2 on 2026-04-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detection_source',
            field=models.CharField(blank=True, choices=[('rule', 'Rule-based'), ('ml', 'ML model'), ('both', 'Rule + ML')], help_text='Populated once the event has been evaluated. Null until processing is complete.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rule_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='log_source',
            field=models.CharField(choices=[('NetworkMonitor', 'Network Monitor'), ('FileMonitor', 'File Monitor'), ('ProcessMonitor', 'Process Monitor'), ('AuthMonitor', 'Authentication Monitor'), ('UsbMonitor', 'USB Monitor'), ('RegistryMonitor', 'Registry Monitor'), ('BrowserExtension', 'Browser Extension')], default='unknown', max_length=100),
        ),
    ]
