# Generated by Django 4.2 on 2026-03-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
